# CHUNG CHO TOÀN BỘ HỆ THỐNG
spring.application.name=distributed-store-coordinator
server.port=8080

# Cấu hình Hibernate chung
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SITE 1: HÀ NỘI (PORT 5431 TRÊN DOCKER)
spring.datasource.hn.jdbc-url=jdbc:postgresql://localhost:5431/sales_db
spring.datasource.hn.username=admin
spring.datasource.hn.password=123456
spring.datasource.hn.driver-class-name=org.postgresql.Driver

# SITE 2: ĐÀ NẴNG (PORT 5434 TRÊN DOCKER)
spring.datasource.dn.jdbc-url=jdbc:postgresql://localhost:5434/sales_db
spring.datasource.dn.username=admin
spring.datasource.dn.password=123456
spring.datasource.dn.driver-class-name=org.postgresql.Driver

# SITE 3: TP.HCM (PORT 5433 TRÊN DOCKER)
spring.datasource.hcm.jdbc-url=jdbc:postgresql://localhost:5433/sales_db
spring.datasource.hcm.username=admin
spring.datasource.hcm.password=123456
spring.datasource.hcm.driver-class-name=org.postgresql.Driver

# CẤU HÌNH CONNECTION POOL (HIKARI) - Tối ưu cho hệ phân tán
spring.datasource.hn.hikari.maximum-pool-size=10
spring.datasource.dn.hikari.maximum-pool-size=10
spring.datasource.hcm.hikari.maximum-pool-size=10

# LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE